base:
  config:
    nacos:
      hostname: nacos.wufan.com
      port: 80

spring:
  application:
    # 应用名称
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    # 使用 Nacos 作为服务注册发现
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        # 采用自定义路由 ID
        - id: BUSINESS-OAUTH2
          # 采用 LoadBalanceClient 方式请求，
          uri: lb://business-oauth2
          # 谓词
          predicates:
            # 路径匹配，以 api 开头
            - Path=/api/user/**
          filters:
            # 前缀过滤
            # 此处配置去掉 1 个路径前缀
            - StripPrefix=1
        - id: BUSINESS-REG
          uri: lb://business-reg
          predicates:
            - Path=/api/reg/**
          filters:
            - StripPrefix=1
        - id: BUSINESS-PROFILE
          uri: lb://business-profile
          predicates:
            - Path=/api/profile/**
          filters:
            - StripPrefix=1
        - id: CLOUD-UPLOAD
          uri: lb://cloud-upload
          predicates:
            - Path=/api/upload/**
          filters:
            - StripPrefix=1
server:
  port: 8888

# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug
